version: 2
jobs:
  deploy-job:
    working_directory: /app
    environment:
      PROJECT_NAME: xxxtestxxx12345
      CLUSTER_NAME: cluster-1
      CLOUDSDK_COMPUTE_ZONE: us-central1-a

    docker:
      - image: google/cloud-sdk
    steps:
      - run:
        name: Store Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
        command: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        command: sudo /opt/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT
